#!/bin/sh
#
# hostname.sh	Set hostname.
#
# Version:	@(#)hostname.sh  1.10  26-Feb-2001  miquels@cistron.nl
#




console=$(fw_printenv console)
console=${console##console=}
br=${console:6:6} 
console=${console:0:5} 
/sbin/getty $br $console
