#!/bin/sh


application=$(fw_printenv application)
EnableCursor=$(fw_printenv EnableCursor)

if [[ -n "$application" ]] ; 
	then
	application=${application##application=}
	
	echo "starting app..."
	#stop output to console
	exec 1>/dev/null 2>/dev/null

	sed -i 's/"exited_cleanly": false,/"exited_cleanly": true,/g' /home/root/.config/chromium/'Local State'
	sed -i 's/"exited_cleanly": false,/"exited_cleanly": true,/g' /home/root/.config/chromium/Default/Preferences
	#'default browser'
	sed -i 's/"check_default_browser": true,/"check_default_browser": false,/g' /home/root/.config/chromium/Default/Preferences
	export DISPLAY=:0.0
	export HOME=/home/root
	. /etc/profile

	
	while [ -z $(ps -ef |grep enlightenment | grep -v grep) ];
	do
	sleep 1
	done 
	sleep 2

	if [ "$EnableCursor" = "EnableCursor=no" ]; then
	/usr/mouse_ptr/hide_curssor.sh &
	fi

	
	
	#endless loop
	while : 
	do
	su -c "$application"
	done	
	
	fi


